# Generated by Django 5.0.6 on 2024-05-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profil_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
